#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service # this field can be anything as long as it is unique
#          uri: lb://PRODUCT-SERVICE
#          predicates: # it is like the condition which is validated against incoming requests
#            - Path=/api/v1/products/**
#
#        - id: user-service # this field can be anything as long as it is unique
#          uri: lb://USER-SERVICE
#          predicates: # it is like the condition which is validated against incoming requests
#            - Path=/api/v1/users/**
#
#        - id: order-service # this field can be anything as long as it is unique
#          uri: lb://ORDER-SERVICE
#          predicates: # it is like the condition which is validated against incoming requests
#            - Path=/api/v1/orders/**, /api/v1/cart/**
#
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - setPath=/
#
#        - id: eureka-static-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**

server:
  port: 8080

# Config setup for defining Resilience4j features like Circuit Breakers, Retry and Rate Limiting
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based