spring:
  datasource:
    url: ${ORDER_MYSQL_URL}
    username: ${ORDER_MYSQL_USERNAME}
    password: ${ORDER_MYSQL_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# Config setup for circuitbreaker health info
  health:
    circuitbreakers:
      enabled: true

# Eureka server URL (where the Eureka server is running)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # Register with Eureka (default is true, but good to be explicit)
    register-with-eureka: true
    # Fetch registry from Eureka (true if the client needs to discover other services)
    fetch-registry: true

# Config setup for defining Resilience4j features like Circuit Breakers, Retry and Rate Limiting
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based