spring:
  datasource:
    url: ${PRODUCT_POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka server URL (where the Eureka server is running)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # Register with Eureka (default is true, but good to be explicit)
    register-with-eureka: true
    # Fetch registry from Eureka (true if the client needs to discover other services)
    fetch-registry: true

#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.user=sa
#spring.datasource.password=