spring:
  datasource:
    url: ${PRODUCT_POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

server:
  port: 8081

#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.user=sa
#spring.datasource.password=